version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=api-proxy.xangnam.com
      - VIRTUAL_HOST=nginx.xangnam.com
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  api-proxy:
    image: lelylanlab/api-proxy:latest
    restart: always
    container_name: api-proxy
    expose:
      - 8000
    depends_on:
      - people
      - devices
      - types
      - subscriptions
      - profiles
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=api-proxy.xangnam.com
      - VIRTUAL_PORT=8000
      - PORT=8000
      - DEBUG=lelylan
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
      - LELYLAN_PEOPLE_PORT=80
      - LELYLAN_DEVICES_PORT=80
      - LELYLAN_TYPES_PORT=80
      - LELYLAN_SUBSCRIPTIONS_PORT=80
      - LELYLAN_PROFILES_PORT=80
      - LELYLAN_PROXY_URL=api-proxy.xangnam.com
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  devices:
    image: lelylanlab/devices:latest
    restart: always
    container_name: devices
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
      - people
      - types
      - subscriptions
      - profiles
    environment:
      - VIRTUAL_HOST=devices.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  mqtt:
    image: lelylanlab/mqtt:latest
    restart: always
    container_name: mqtt
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=mqtt.xangnam.com
      - REDIS_HOST=redis
      - DEBUG=lelylan
      - NODE_PORT=1883
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  nodes:
    image: lelylanlab/nodes:latest
    restart: always
    container_name: nodes
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis
      - memcached
      - api-proxy
      - mqtt
    environment:
      - VIRTUAL_HOST=nodes.xangnam.com
      - VIRTUAL_PORT=8000
      - PORT=8000
      - MOSCA_HOST=mqtt
      - REDIS_HOST=redis
      - LELYLAN_API_URL=http://api-proxy:8000
      - LELYLAN_API_HOST=api-proxy.xangnam.com
      - DEBUG=lelylan
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
      - "mqtt:mqtt"
      - "api-proxy:api-proxy"
  people:
    image: lelylanlab/people:latest
    restart: always
    container_name: people
    expose:
      - 80
    depends_on:
      - types
      - subscriptions
      - profiles
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=people.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
      - LELYLAN_DEV_URL=dev-center.xangnam.com
      - LELYLAN_DEV_PORT=80
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  physicals:
    image: lelylanlab/physicals:latest
    restart: always
    container_name: physicals
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=physicals.xangnam.com
      - RACK_ENV=development
      - RAILS_ENV=development
      - DEBUG=lelylan
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  profiles:
    image: lelylanlab/profiles:latest
    restart: always
    container_name: profiles
    expose:
      - 80
    depends_on:
      - types
      - subscriptions
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=profiles.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  subscriptions:
    image: lelylanlab/subscriptions:latest
    restart: always
    container_name: sub
    expose:
      - 80
    depends_on:
      - types
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=subscriptions.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  types:
    image: lelylanlab/types:latest
    restart: always
    container_name: types
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=types.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  webhooks:
    image: lelylanlab/webhooks:latest
    restart: always
    container_name: webhooks
    expose:
      - 80
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=webhooks.xangnam.com
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
      - DEBUG=true
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  websockets:
    image: lelylanlab/websockets:latest
    restart: always
    container_name: websockets
    expose:
      - 8000
    depends_on:
      - mongodb
      - redis
      - memcached
    environment:
      - VIRTUAL_HOST=websockets.xangnam.com
      - VIRTUAL_PORT=8000
      - DEBUG=lelylan
      - PORT=8000
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_DEVICES_URL=devices
      - LELYLAN_TYPES_URL=types
      - LELYLAN_SUBSCRIPTIONS_URL=subscriptions
      - LELYLAN_PROFILES_URL=profiles
      - MONGOLAB_PEOPLE_URL=mongodb://mongodb:27017/people
      - MONGOLAB_DEVICES_URL=mongodb://mongodb:27017/devices
      - MONGOLAB_TYPES_URL=mongodb://mongodb:27017/types
      - MONGOLAB_JOBS_URL=mongodb://mongodb:27017/jobs
      - MONGOLAB_SUBSCRIPTIONS_URL=mongodb://mongodb:27017/subscriptions
      - MONGOLAB_LOCATIONS_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/
      - REDIS_RATE_LIMIT_URL=redis://redis:6379/
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=hex
      - MEMCACHIER_PASSWORD=ilovedocker555
    links:
      - "people:people"
      - "devices:devices"
      - "types:types"
      - "subscriptions:subscriptions"
      - "profiles:profiles"
      - "mongodb:mongodb"
      - "redis:redis"
      - "memcached:memcached"
  #: Development tools
  types-dashboard:
    image: lelylanlab/types-dashboard-ng:latest
    restart: always
    container_name: type-dashboard
    expose:
      - 80
    depends_on:
      - api-proxy
      - people
      - websockets
    environment:
      - VIRTUAL_HOST=types-dashboard.xangnam.com
      - PUBLIC_HOST=types-dashboard.xangnam.com
      - LISTEN_HOST=0.0.0.0
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_API_PUBLIC_URL=api-proxy.xangnam.com
      - LELYLAN_PEOPLE_PUBLIC_URL=people.xangnam.com
      - LELYLAN_CLIENT_ID=""
      - LELYLAN_TYPES_DASHBOARD_PUBLIC_URL=types-dashboard.xangnam.com
      - LELYLAN_DEVICES_DASHBOARD_PUBLIC_URL=devices-dashboard.xangnam.com
      - LELYLAN_WEBSOCKETS_PUBLIC_URL=websockets.xangnam.com
      - LELYLAN_DEV_CENTER_PUBLIC_URL=dev-center.xangnam.com
      - LELYLAN_NODES_PUBLIC_URL=nodes.xangnam.com
  devices-dashboard:
    image: lelylanlab/devices-dashboard-ng:latest
    restart: always
    container_name: devices-dashboard
    expose:
      - 80
    depends_on:
      - api-proxy
      - people
      - websockets
    environment:
      - VIRTUAL_HOST=devices-dashboard.xangnam.com
      - PUBLIC_HOST=devices-dashboard.xangnam.com
      - LISTEN_HOST=0.0.0.0
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_API_PUBLIC_URL=api-proxy.xangnam.com
      - LELYLAN_PEOPLE_PUBLIC_URL=people.xangnam.com
      - LELYLAN_CLIENT_ID="55765567"
      - LELYLAN_DEVICES_DASHBOARD_PUBLIC_URL=devices-dashboard.xangnam.com
      - LELYLAN_TYPES_DASHBOARD_PUBLIC_URL=types-dashboard.xangnam.com
      - LELYLAN_WEBSOCKETS_PUBLIC_URL=websockets.xangnam.com
      - LELYLAN_DEV_CENTER_PUBLIC_URL=dev-center.xangnam.com
      - LELYLAN_NODES_PUBLIC_URL=nodes.xangnam.com
  dev-center:
    image: lelylanlab/dev:latest
    restart: always
    container_name: dev-center
    expose:
      - 80
    depends_on:
      - people
    environment:
      - VIRTUAL_HOST=dev-center.xangnam.com
      - PORT=80
      - RACK_ENV=development
      - RAILS_ENV=development
      - NODE_ENV=development
      - LELYLAN_PEOPLE_URL=people
      - LELYLAN_PEOPLE_PORT=80

  mongodb:
    image: mongo:2.6
    restart: always
    container_name: mongodb
    volumes_from:
      - mongodb-data
    expose:
      - 27017
    command: mongod --smallfiles
  mongodb-data:
    image: mongo:2.6
    container_name: mongodb-data
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
  redis:
    image: redis:2.6
    restart: always
    container_name: redis
    volumes_from:
      - redis-data
    expose:
      - 6379
  redis-data:
    image: redis:2.6
    container_name: redis-data
    volumes:
      - /data
    entrypoint: /bin/true
  memcached:
    image: bitnami/memcached:latest
    restart: always
    container_name: memcached
    expose:
      - 11211
    environment:
      - MEMCACHED_USERNAME=hex
      - MEMCACHED_PASSWORD=ilovedocker555
